# Generated by Django 5.1.3 on 2025-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('userid', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rollno', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
